project2/auction/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import login

app_name = 'auction'

urlpatterns = [

    url(r'^home/$', views.HomeView.as_view(), name='home'),

    url(r'^$', login, {'template_name': 'auction/login.html'}, name='login'),

    url(r'^register/$', views.UserReg.as_view(), name='user'),

    url(r'^home/productreg/$', views.ProductReg.as_view(), name='product-reg'),

    url(r'^home/category/product/(?P<pk>[0-9]+)/$', views.ProductDetail.as_view(), name='product-detail'),

    url(r'^home/category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category-page'),

    url(r'^home/category/product/bid/(?P<pk>[0-9]+)/$', views.BidView.as_view(), name='bid-page'),
]

project2/project2/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^auction/', include('auction.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project2/auction/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.core.urlresolvers import reverse
from django.db import models


class category(models.Model):

    category_name = models.CharField(max_length=100)

    def __str__(self):
        return self.category_name


class product(models.Model):
    product_name = models.CharField(max_length=100)
    p_category = models.ForeignKey(category, on_delete=models.CASCADE)
    price = models.FloatField()
    start = models.TimeField()
    image = models.FileField()
    highest = models.CharField(max_length=200, default=0)
    status = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('auction:product-detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.product_name + '-' + str(self.p_category)

project2/auction/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import product


class UserRegForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password', 'email']


class BidForm(forms.ModelForm):

    class Meta:
        model = product
        fields = ['price']

project2/auction/views.py
from __future__ import unicode_literals

import datetime
from django.contrib.auth import authenticate, login
from django.shortcuts import redirect
from django.shortcuts import render
from django.urls import reverse
from django.views import generic
from django.views.generic import View, CreateView, UpdateView
from .forms import UserRegForm, BidForm
from .models import category, product


class CategoryView(generic.ListView):
    template_name = 'auction/category.html'
    context_object_name = 'all_products'

    def get_queryset(self):
        print self.kwargs['pk']
        return product.objects.filter(status=False, p_category=self.kwargs['pk'])


class HomeView(generic.ListView):
    template_name = 'auction/home.html'
    context_object_name = 'all_categories'

    def get_queryset(self):
        return category.objects.all()


class ProductDetail(generic.DetailView):
    model = product
    template_name = 'auction/product.html'

    def get_queryset(self):
        user = product.objects.get(pk=self.kwargs['pk'])
        star = user.start
        x = datetime.timedelta(minutes=30)
        end = (datetime.datetime.combine(datetime.date.today(), star) + x).time()
        time_now = datetime.datetime.now()
        t = time_now.time().replace(microsecond=0)
      
        if t >= end:
            user.status = True
            user.save()
        return product.objects.filter(pk=self.kwargs['pk'])


class UserReg(View):
    form_class = UserRegForm
    template_name = 'auction/registration_form.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)

            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            email = form.cleaned_data['email']
            user.set_password(password)
            user.save()

            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('auction:home')

        return render(request, self.template_name, {'form': form})


class ProductReg(CreateView):
    model = product
    fields = ['product_name', 'p_category', 'price', 'start', 'image']


class BidView(UpdateView):
    form_class = BidForm
    model = product
    # fields = ['price']
    template_name = 'auction/bid_page.html'
    sold = []

    def post(self, request, pk):
        user = product.objects.get(pk=pk)
        bid = float(request.POST['price'])
        # do backend authentication, verify time difference here
        start = user.start
        x = datetime.timedelta(minutes=30)
        end = (datetime.datetime.combine(datetime.date.today(), start) + x).time()
        time_now = datetime.datetime.now()
        t = time_now.time().replace(microsecond=0)
        print time_now
        print start
        if t >= start and t <= end:
            if bid > user.price:
                user.highest = request.user.username
                user.price = bid
                user.status = True
                user.save()

        return redirect(reverse('auction:product-detail', kwargs={'pk': pk}))

project2/auction/templates/auction/bid_page.html
<h1>Bid for {{ product.product_name }}</h1>

<form method="post">
    {% csrf_token %}
    {% include 'auction/form_template.html' %}
    <button type="submit" value="{{ product.price }}">Bid</button>
</form>

project2/auction/templates/auction/category.html
<ul>

    {% for product in all_products %}

        <li><a href="{% url 'auction:product-detail' product.pk %}">{{ product.product_name }}</a></li>

        <img src="{{ product.image.url }}">

    {% endfor %}

</ul>

project2/auction/templates/auction/form_template.html
{% for field in form %}
    <span>{{ field.errors }}</span>
    <label>{{ field.label_tag }}</label>
    <span>{{ field }}</span><br>
{% endfor %}

project2/auction/templates/auction/home.html
<h1> WELCOME TO HOMEPAGE </h1>

{% if user.is_active %}
    <h3>Welcome {{ request.user.username }}</h3>
    <ul>
{% for category in all_categories %}

    <li> <a href="{% url 'auction:category-page' category.pk %}"><label>{{ category.category_name }}</label></a></li>

{% endfor %}
    </ul>

    <a href="{% url 'auction:product-reg' %}">Click here to sell a product</a>

{% endif %}

project2/auction/templates/auction/login.html
<h1>Login</h1>

<form method="post">
{% csrf_token %}
{{ form.as_p }}
    <button type="submit">Login</button>

</form>

<a href="{% url 'auction:user' %}">register here</a>

project2/auction/templates/auction/product.html
<body>

<img src="{{ product.image.url }}">
<h2>{{ product.product_name }}</h2>
<h4>{{ product.p_category }}</h4><br>

<h4>Auction Starts at: </h4>
<p id="start">{{ product.start|date:"SHORT_DATE_FORMAT" }} {{ product.start|time:'H:i' }}</p>
<h4>Current bid: {{ product.price }}</h4>
<p id="timer"> </p>
<p id="check"></p>
<p id="check1"></p>
<p id="check2"></p>


<a href="{% url 'auction:bid-page' product.pk %}"><button style="display: none" id="form1">Bid here</button></a>



<script>

    var start = document.getElementById("start").innerHTML;
    var n = new Date();

    var today = new Date();
    var dd = today.getDate();
    var mm = today.getMonth()+1; //January is 0!
    var yyyy = today.getFullYear();

    if(dd<10){
    dd='0'+dd;
    }
    if(mm<10){
    mm='0'+mm;
    }
    var tod = mm+'/'+dd+'/'+yyyy;




    var s = Date.parse(tod); //gives milliseconds from jan 1 1970 to given date 00:00



    // calculate milliseconds to start time and add to s
    var a = start.slice(0,3); //return hh
    var b = start.slice(4,6); //return mm
    var startTime = s + a * 3600000 + (b / 60) * 3600000;

    // calculate milliseconds from start time to end time and store
    var endTime = startTime + 1800000;

    //convert start time and end time to date object
    var startDate = new Date(startTime);
    var endDate = new Date(endTime);

    //countdown timer
    var now = new Date();
    var d = new Date(now);
    var milliseconds = d.getTime();

    //document.getElementById("check").innerHTML = new Date(tod);
    //document.getElementById("check1").innerHTML = new Date(endTime);
    //document.getElementById("check2").innerHTML = milliseconds;

    if(milliseconds >= startTime & milliseconds <= endTime){
       document.getElementById("form1").style.display="block";

        var countDownDate = endDate.getTime();
        //document.getElementById("demo").innerHTML = countDownDate;
        var x = setInterval(function() {
            var now = new Date().getTime();
            var distance = countDownDate - now;

        var days = Math.floor(distance / (1000 * 60 * 60 * 24));
        var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
        var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
        var seconds = Math.floor((distance % (1000 * 60)) / 1000);


         document.getElementById("timer").innerHTML = days + "d " + hours + "h " + minutes + "m " + seconds + "s ";
          if (distance < 0) {
           clearInterval(x);
           document.getElementById("timer").innerHTML = "Auction completed.";
           document.getElementById("form1").style.display="none";
          }
        },1000);
    }
    else if (milliseconds > endTime){
        document.getElementById("timer").innerHTML ="The auction is over!";

    }
    else if(milliseconds < startTime){
        document.getElementById("timer").innerHTML ="The auction hasn't started yet!";
    }





</script>

</body>

project2/auction/templates/auction/product_form.html
<h1>Enter Product details</h1>

<h2>NOTE: Please enter start time in this format: 'hh:mm'</h2>
<h2>All auctions are conducted on the same day of registration.</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% include 'auction/form_template.html' %}
    <button type="submit">Submit</button>
</form>

project2/auction/templates/auction/registration_form.html
<form method="post">
    {% csrf_token %}

{% include 'auction/form_template.html' %}

    <button type="submit">Submit</button>
</form>